import os

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
SF_CLIENT_ID = os.getenv("SF_CLIENT_ID")
SF_CLIENT_SECRET = os.getenv("SF_CLIENT_SECRET")
SF_USERNAME = os.getenv("SF_USERNAME")
SF_PASSWORD = os.getenv("SF_PASSWORD")
SLACK_WEBHOOK = os.getenv("SLACK_WEBHOOK")